// ignore: file_names

import 'package:flutter/material.dart';
import 'package:test_/model/condition_model.dart';
import 'package:test_/service/condition.dart';

class ConditonUI extends StatefulWidget {
  const ConditonUI({Key? key}) : super(key: key);

  @override
  State<ConditonUI> createState() => _ConditonUIState();
}

class _ConditonUIState extends State<ConditonUI> {
  ConditionModel? autogenerated;
  Data data = Data();

  @override
  void initState() {
    data.fetchData().then((value) {
      setState(() {
        autogenerated = value;
      });
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      backgroundColor: const Color(0xffe6f2eb),
      body: autogenerated == null
          ?const Center(child:  CircularProgressIndicator())
          : Column(
              children: [
                const Center(
                    child: Padding(
                      padding: EdgeInsets.only(top: 60.0),
                      child: Text(
                  "Condition",
                  style: TextStyle(color: Color(0xfff4991c),fontSize: 30),
                ),
                    )),
                Expanded(
                  child: ListView.builder(
                    itemCount: autogenerated?.articles!.length,
                    itemBuilder: (context, index) => Padding(
                        padding: const EdgeInsets.all(16.0),
                        child: Row(
                          children: [
                            Text("${index+1} )",
                                style:const TextStyle(color: Color(0xfff4991c))),
                            Container(
                                child: Flexible(
                                    child: Text(
                                        "${autogenerated?.articles![index].description}",
                                        maxLines: 20)))
                          ],
                        )),
                  ),
                ),
              ],
            ),
    );

    // ignore: dead_code
  }
}
